### ISSUE TITLE
Add Card for contact info

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#11]
<img width="305" alt="screen shot 2017-03-26 at 11 01 58 am" src="https://cloud.githubusercontent.com/assets/9954667/24333366/bdc6428a-1213-11e7-9ced-76004cb90f5f.png">

**Comment by SOSA1095** [comment]
https://m.popkey.co/b39013/J6lrl_s-200x150.gif

**Comment by SOSA1095** [comment]
https://m.popkey.co/b39013/J6lrl_s-200x150.gif
