### ISSUE TITLE
Agregar opción de "Solicitudes" en el action bar

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#21]
Agregar un item en menu_main.xml con showAsAction="never"

**Comment by SOSA1095** [comment]
![2kt2pncv1ul8jfj89yj3mex9xujsbjah02vkxxb0zp9ggyl13llirmvkrdj28f5](https://cloud.githubusercontent.com/assets/8510160/24372200/6783c8a2-12ea-11e7-8189-c462550c382a.jpg)

**Comment by jorgegil96** [comment]
<img width="333" alt="screen shot 2017-03-27 at 1 08 34 pm" src="https://cloud.githubusercontent.com/assets/9954667/24373426/8cdf068a-12ee-11e7-8be6-433ed509e9db.png">  

![back-to-work-memes-06-640x640](https://cloud.githubusercontent.com/assets/9954667/24373431/91baeff2-12ee-11e7-8029-13e3319d4f26.jpg)
