### ISSUE TITLE
Completar publicación de un ride

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#27]
En PostActivity, sacar la información del ride creado y guardarlo en el repository.

Tienes que sacar la información que lleno el usuario en el on click del boton para publicar, luego sacas informacion basica del usuario (id, name, photo), y creas los objetos Ride y User(del package de firebase) y mandas llamar al presenter.saveRide()

**Comment by SOSA1095** [comment]
![4472a431141700526886054168_700wa_0](https://cloud.githubusercontent.com/assets/8510160/24568104/dd9b958e-161d-11e7-9ee0-2ee1cf75b701.gif)
