### ISSUE TITLE
Implementar métodos de Leer/Guardar id del usuario en SharedPreferences

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#30]
En AppRepository.java implementar los métodos saveMyId() y getMyId() escribiendo/leyendo desde sharedpreferences.

https://developer.android.com/training/basics/data-storage/shared-preferences.html#WriteSharedPreference

La referencia a sharedpreferences ya está en la clase, no tienes que crearla, sólo haces lo del Editor para escribir o los getString para leer.

**Comment by SOSA1095** [comment]
![d0d4622c144944007171417452_700wa_0](https://cloud.githubusercontent.com/assets/8510160/24568076/b841a436-161d-11e7-8389-471898f58c08.gif)
