### ISSUE TITLE
Hacer activity para pedir información de usuario la primera vez que haga la app

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#35]
Incluir:  
* Textview para matricula, nombre y apellido (no modificable)  
* Su ubicacion (usar fragment igual al del activity de publicar)  
* elegir entre fumar o no  
* elegir pasajeros hombre y mujer o ambos  
* costo
* edittext para notas

**Comment by SOSA1095** [comment]
![oafbxrx](https://cloud.githubusercontent.com/assets/8510160/25315893/72087f5a-2822-11e7-956c-b67162441a79.gif)
