### ISSUE TITLE
Indicar al usuario la información suya que compartira al aceptar una solicitud

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#59]
Usa MaterialDialogs https://github.com/afollestad/material-dialogs

Ejemplo

new MaterialDialog.Builder(this)
        .title(R.string.title)
        .content(R.string.content)
        .positiveText(R.string.agree)
        .negativeText(R.string.disagree)
        .onPositive(new blabla.... -> accion al hacer click en ok)
        .show();

**Comment by SOSA1095** [comment]
![sssssssssssssssssssssssssssssssssssssssssssssssssssss](https://cloud.githubusercontent.com/assets/8510160/25980844/f0b0f562-3696-11e7-8773-c4114386f26f.gif)
