### ISSUE TITLE
Agregar ubicacion de casa en actividad de pedir info

### ISSUE THREAD

**Issue by jorgegil96** [SilvaMtz/Carpooling#62]
Guardala en sharedprefs, ya hay dos metodos en AppRepority `setMyLatitude` y `setMyLongitude`

**Comment by SOSA1095** [comment]
![tumblr_inline_olct60a7jp1tmey96_500](https://cloud.githubusercontent.com/assets/8510160/25923433/22e82c5c-35a3-11e7-8004-a5fb95f94340.gif)
